# Generated by Django 5.1.7 on 2025-04-01 14:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
                ('status', models.CharField(choices=[('未完了', '未完了'), ('進行中', '進行中'), ('完了', '完了')], default='未完了', max_length=10, verbose_name='ステータス')),
                ('priority', models.IntegerField(default=0, verbose_name='優先度')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='期限')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-priority', 'due_date', '-created_at'],
            },
        ),
    ]
